## 簡介

R 語言翻轉教室除了教R 之外，另外一個理念是想要教同學培養工具的自學能力。

為了協助老師上的教學使用，
我們收集各種R 在各種領域的應用實例的文章，
並且撰寫相關的小測驗，
讓同學在閱讀之後可以做測驗，
並且老師們可以掌握同學的自學狀況。

## 閱讀專區

- [正則表示式：文字處理的大絕招](https://datascienceandr.org/articles/RegularExpression.html)

### Taiwan R User Group 專區

這裡紀錄許多社群分享的文章

- [如何讓R與Java溝通 - rJava](https://programmermagazine.github.io/201308/htm/article5.html)
- [R 講題分享 - 種類數的估計與預測](https://programmermagazine.github.io/201312/htm/article6.html)
- [R 講題分享 – SpideR -- 用R自製網路爬蟲收集資料 (作者：Taiwan R User Group)](https://programmermagazine.github.io/201311/htm/article6.html)

### [celestialgod](https://chingchuan-chen.github.io/) 專區

- [在R用ROracle去操作Oracle資料庫](https://chingchuan-chen.github.io/posts/2016/07/25/use-ROracle-to-manipulate-oracle-database-in-R)
- [Pipe Operators in R](https://chingchuan-chen.github.io/posts/2016/07/10/pipe-operators-in-R)
- [introduction to magrittr](https://chingchuan-chen.github.io/posts/2015/07/01/magrittr)
- [introduction to data.table](https://chingchuan-chen.github.io/posts/2015/07/02/data-table)
- [introduction to dplyr](https://chingchuan-chen.github.io/posts/2015/07/03/dplyr)
- [introduction to tidyr](https://chingchuan-chen.github.io/posts/2015/07/04/tidyr)
- [R web service with opencpu](https://chingchuan-chen.github.io/posts/2016/10/21/R-web-service-with-opencpu
)
- [A comparison for R parallel packages](https://chingchuan-chen.github.io/posts/2016/11/26/R-parallel-pkgs)
- [Differences between RcppEigen and RcppArmadillo](https://chingchuan-chen.github.io/posts/2016/12/31/Differences-between-RcppEigen-and-RcppArmadillo
)
- [Using caret to tune the model parameters](https://chingchuan-chen.github.io/posts/2017/03/14/using-caret-to-tune-model-parameters)
- [Grid search in data.table](https://chingchuan-chen.github.io/posts/2017/04/10/grid-search-in-data.table
)
- [ptt問答: parsing的中文顯示](https://www.ptt.cc/bbs/R_Language/M.1466658481.A.FAB.html)
- [ptt問答：爬蟲爬取聯合財經新聞](https://www.ptt.cc/bbs/R_Language/M.1480080483.A.5F6.html)
- [ptt問答：零基礎的網頁Parse?](https://www.ptt.cc/bbs/R_Language/M.1465313901.A.EE1.html)

### Wush 專區

這裡紀錄了我個人有參與的R 相關著作

- [Self-Updating Process Clustering](https://cran.r-project.org/package=supc/vignettes/supc.html)
- [RcppCNPy: Reading and writing NumPy binary files](https://cran.r-project.org/package=RcppCNPy/vignettes/RcppCNPy-intro.pdf)
- [FeatureHashing](https://cran.r-project.org/package=FeatureHashing/vignettes/FeatureHashing.html)
- [Sentiment Analysis via R, FeatureHashing and XGBoost](https://cran.r-project.org/package=FeatureHashing/vignettes/SentimentAnalysis.html)
- [Serialize and Deserialize a C++ Object in Rcpp](https://gallery.rcpp.org/articles/rcpp-serialization/)
- [Call Python from R through Rcpp](https://gallery.rcpp.org/articles/rcpp-python/)
- [利用R處理大量的JSON資料 （Streaming Style）](https://wush.ghost.io/r-jsonlines/)
- [itertools簡介](https://wush.ghost.io/itertools-intro/)
- [dplyr::group_by的進階應用](https://wush.ghost.io/dplyr_group_by/)
- [R的除錯功能](https://wush.ghost.io/r-debug/)
- [從R語言翻轉教室到機器學習](slide/DSRToML.html) <iframe width="560" height="315" src="https://www.youtube.com/embed/zax6l3ilg2A" frameborder="0" allowfullscreen></iframe>

