<!-- scripts: [{"src" : "https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"}] -->
<!-- header-meta: [{"name" : "google-signin-client_id", "content" : "842324757776-nonjllne8m8as9djg51e6cg98h6ijam7.apps.googleusercontent.com"}] -->
<!-- header-link: [{"href" : "https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css", "rel" : "stylesheet"}] -->

## 帳務專區

登入後，會將您的追蹤紀錄顯示於下方。

`r paste(readLines("chunks/login.md"), collapse="\n")`

## 報表專區

<div id="report_container">
</div>

<div id="fb-root"></div>

<script type="text/javascript">
var datascienceandrUserData;
var datascienceandrGetUserData = function() {
  $.ajax({
    url : datascienceandrUrls() + "/api/auth/getCurrentUserRecords",
    type : "POST",
    data : {},
    dataType : "json",
    success : function(data) {
      datascienceandrUserData = data;
      datascienceandrOverlayDiv.hide();
    },
    complete : datascienceandrRenderUserData,
    error: function(jqXHR, textStatus, errorThrown) {
      throw errorThrown;
    },
    timeout : 5000,
    xhrFields: {
      withCredentials: true
    },
    crossDomain: true
  });
};
var datascienceandrRenderUserData = function() {
  var div = $("#report_container");
  div.empty();
  var src = '<div id="user_id" style="text-align : center;"><h3>以下是' + datascienceandrUser + '的操作紀錄</h3></div>' +
    '<table id="used_record_table" class="display">' +
    '<thead><td>課程名稱</td><td>單元名稱</td><td>進入/完成</td><td>時間</td></tr></thead>' +
    "<tfoot><tr><td>課程名稱</td><td>單元名稱</td><td>進入/完成</td><td>時間</td></tr></tfoot>" +
    "<tbody>";
  _.forEach(datascienceandrUserData, function(record) {
    var result = "<tr><td>" +
      record.course.split(":")[0] +
      "</td><td>" +
      record.course.split(":")[1] +
      "</td><td>" +
      (record.type == 1 ? "完成" : "進入") +
      "</td><td>" +
      record.created_at +
      "</td></tr>";
    src += result;
  });
  src += "</tbody>";
  div.append(src);
  $("#used_record_table").DataTable({"columnDefs" : []});
};
</script>